### ISSUE TITLE
can support ipod classic ？

### ISSUE THREAD

**Issue by buzai** [crozone/ipodloader2#4]

**Comment by crozone** [comment]
iPod Loader 2 only works with PortalPlayer based iPods, which goes up to the iPod Video 5.5G. Unfortunately the iPod Classic 6G uses a completely different platform based on a Samsung ARM CPU.

You may want to look at using the [EmCORE bootloader](https://freemyipod.org/wiki/EmCORE#emCORE_boot_menu), which may let you get similar functionality on Classic 6G.
